#!/bin/sh

rm -r BUILD/*
mkdir BUILD/desktop
mkdir BUILD/desktopwidgets
mkdir BUILD/loaders

echo "*** BOOTLOADER ***"
cd bootloader
make
cd ..

echo "*** KERNEL ***"
cd kernel
make
cd ..

echo "*** DESKTOP ***"
cd desktop
make
cd ..

echo "*** POP ***"
cd pop
make
cd ..

echo "*** DWHELLOWORLD ***"
cd dwHelloWorld
make
cd ..

echo "*** DWTOTEM ***"
cd dwTotem
make
cd ..

# ./run
