
enum TagType {
    TAG_PADDING = 0,
    TAG_INDEX,
    TAG_OFFSETADDRESS,
    TAG_CODECHUNK,
    TAG_ENTRYPOINT,
    TAG_CRC,
    TAG_HAT,
    TAG_LONGNAME,
    TAG_AUTHOR,
    TAG_DESCRIPTION,
    TAG_IMG_36X36_4BPP,
    TAG_IMG_24X24_4BPP,
    TAG_IMG_100X24_4BPP,
    TAG_IMG_110X88_4BPP,
    TAG_CODE = 0X10008000,
};

